// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yybuzcavdmmjxtefoqgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YnV6Y2F2ZG1tanh0ZWZvcWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzI5MzYsImV4cCI6MjA2MzYwODkzNn0.0XMpEaM_unvXlOE1Gh8GsIwfmrgORaVV2MUn6TrWYJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);